---
title: Demo
listing: 
  - id: Examples
    contents: 
      - _crossrefs/exm.yml
      - _crossrefs
    type: table
    sort: false
    page-size: 20
    fields: [description, type, link]
    field-display-names: 
      description: Description
      type: Type
      link: Link
---

# Demo of crossref-listings

## Description

This filter automates the creation of listings of cross-referenced items. Say you have a book project over multiple files, and it includes many formal `example` divs, such as the following.

::::{#exm-example1 description="A fine example" type=Code}
## Good example
This is example 1.
::::

There may be examples on pages throughout the book. Your readers might like to have a one-stop summary of all of them. But this is tedious and fragile for you to do by hand.

Instead, you could simply have the following.

### Table of examples {.unnumbered}

This directory of examples is updated each time the website is rendered. Note that it includes material from the entire project, not just this page.

:::{#Examples}
:::

## Installation {#sec-install}

At the command line and in the project's root directory, enter 

```bash
quarto install extension tobydriscoll/crossref-listings
```

This has to be done for each project where you want to use the extension. 

### Optional (recommended) {.unnumbered}

If you are comfortable installing Python on your system, then install the `quarto`, `pandoc`, and `yaml` packages to use a faster and more convenient method with the extension.

