# Limitations

This extension would be much better if I understood more about how Quarto works. A Pandoc filter only gets to look at one file at a time. The AST is built, modified, and then written. That makes cross-references impossible at that level. Quarto obviously operates at a higher level where all that is orchestrated together, but it's opaque to me. Hence, my filter dumps the cross-references into files that are concatenated together in order to be read on the next full rendering.

::: {.callout-tip}
If things get into a hopeless state, it's okay to wipe everything in the `_crossrefs` directory and render twice from scratch.
:::

Alas, I don't know a way to control the page order in which the crossrefs will be assembled. That's because each page is its own world inside its filter, and there is no way to know where it stands relative to the others. Nor can you simply sort on the link name, because "Example 1.10" will come before "Example 1.2". A workaround is to add a chapter number to the attributes for sorting; within each chapter, the ordering should be correct, assuming the listing sort algorithm is stable.

The listings mechanism is powerful but limited in scope. All it will do is mine a directory of markdown files for metadata or take a single file of collected metadata. That makes sense for its intended use case, but it's a straitjacket for more general uses.
